'use strict';
window.KBRDeferred=(()=>{
let accounts=[],entries=[],loading=false;const expandedCustomers=new Set();
function money(n){return peso(Number(n)||0);}
function cashPad(id,amounts){return `<div class="barista-cash-layout" style="grid-template-columns:1fr 1fr"><div class="cash-pane"><div class="cash-quick-title">Quick cash</div><div class="cash-quick-buttons">${amounts.map(n=>`<button type="button" onclick="KBRDeferred.cashQuick('${id}',${n})">₱${n}</button>`).join('')}</div><p class="muted">Quick cash fills the amount applied, up to the bill balance.</p></div><div class="cash-pane"><div class="cash-quick-title">Cash keypad</div><div class="cash-keypad">${[1,2,3,4,5,6,7,8,9].map(n=>`<button type="button" onclick="KBRDeferred.cashKey('${id}','${n}')">${n}</button>`).join('')}<button type="button" class="cash-key-action" onclick="KBRDeferred.cashKey('${id}','clear')">Clear</button><button type="button" onclick="KBRDeferred.cashKey('${id}','0')">0</button><button type="button" onclick="KBRDeferred.cashKey('${id}','back')" aria-label="Delete last digit">⌫</button><button type="button" onclick="KBRDeferred.cashKey('${id}','.')">.</button></div></div></div>`;}
function cashQuick(id,amount){const input=document.getElementById(id);if(!input)return;input.value=String(Math.min(amount,input.max!==''&&Number.isFinite(Number(input.max))?Number(input.max):amount));input.form?.oninput?.({target:input});}
function cashKey(id,key){const input=document.getElementById(id);if(!input)return;let value=String(input.value||'');if(key==='clear')value='0';else if(key==='back')value=value.slice(0,-1)||'0';else if(key==='.')value=value.includes('.')?value:(value||'0')+'.';else if(/^\d$/.test(key)){if(value.includes('.')&&value.split('.')[1].length>=2)return;value=(value+key).replace(/^0+(?=\d)/,'');}else return;if(value.length>12)return;input.value=value;input.form?.oninput?.({target:input});}
function panel(){const order=getCurrentBaristaOrder(),total=pendingOrderTotal(order),host=document.getElementById('baristaPaymentPanel');if(!order||!host)return;
 const later=selectedBaristaPayment==='pay-later',cash=Math.min(Number(cashReceived)||0,total);
 host.innerHTML=`<form id="arrangementForm" class="barista-pay-panel"><b>${later?'Pay Later / Utang':'Cash + GCash split payment'}</b><p>Total: ${money(total)}</p>${later?'<label>Customer name<input name="customer" required minlength="2" maxlength="100" autocomplete="off" placeholder="Who will pay this bill?"></label>':''}<label>Cash paid now<input id="arrangementCash" name="cash" type="text" inputmode="decimal" pattern="[0-9]+([.][0-9]{0,2})?" max="${total}" value="${cash}" required></label>${cashPad('arrangementCash',later?[5,10,15,20]:[50,100,500])}${later?'':`<label>GCash paid now<input name="gcash" type="number" min="0" max="${total}" step="0.01" value="${Math.round((total-cash)*100)/100}" required></label>`}<p id="arrangementBalance"></p><p class="muted">${later?'Enter zero if nothing was paid. The remaining amount stays on this customer’s bill.':'The rest is filled as GCash when you change cash. Confirm the GCash transfer before saving.'}</p><button id="arrangementSubmit" type="submit" class="barista-close-pay">${later?'Confirm Pay Later':'Confirm split payment'}</button></form>`;
 const form=document.getElementById('arrangementForm'),update=e=>{const cash=Number(form.elements.cash.value);if(!later&&e?.target===form.elements.cash)form.elements.gcash.value=String(Math.max(0,Math.round((total-cash)*100)/100));const gcash=later?0:Number(form.elements.gcash.value),debt=Math.round((total-cash-gcash)*100)/100;document.getElementById('arrangementBalance').textContent='Remaining: '+money(debt);document.getElementById('arrangementSubmit').disabled=!Number.isFinite(cash)||cash<0||cash>total||!Number.isFinite(gcash)||gcash<0||debt<0||(!later&&Math.abs(debt)>0.001);};form.oninput=update;update();
 form.onsubmit=async e=>{e.preventDefault();const cash=Number(form.elements.cash.value),gcash=later?0:Number(form.elements.gcash.value);if(!Number.isFinite(cash)||cash<0||cash>total){alert('Cash applied must be between zero and the bill total.');return;}if(!later&&Math.abs(cash+gcash-total)>0.001){alert('Cash and GCash must equal the bill total. Use Pay Later for an unpaid balance.');return;}await window.savePaymentArrangement('kbr_arrange_payment',{p_order:order._cloudId,p_revision:order._cloudRevision,p_cash:cash,p_gcash:gcash,p_customer:form.elements.customer?.value||'',p_operation:KBRCloud.uuid()});};
}
async function refresh(){if(loading)return;loading=true;try{const result=await Promise.all([KBRCloud.rows('/rest/v1/kbr_payment_accounts?select=*&order=created_at.desc'),KBRCloud.rows('/rest/v1/kbr_payment_entries?select=*&order=recorded_at.asc')]);accounts=result[0];entries=result[1];render();}catch(e){const host=document.getElementById('baristaPayLaterView');if(host&&baristaView==='pay-later')host.innerHTML='<p>Could not load Pay Later bills. Check your connection and try again.</p><button onclick="KBRDeferred.refresh()">Retry</button>';}finally{loading=false;}}
function dateTime(value){const date=new Date(value);return Number.isNaN(date.getTime())?'Date not recorded':date.toLocaleString('en-PH',{timeZone:'Asia/Manila'});}
function billOrder(a){return [...pendingOrders,...servedUnpaidOrders,...unservedPaidOrders].find(o=>o._cloudId===a.order_id)||history.find(r=>r._cloudId===a.order_id);}
function orderLines(order){return (order?.items||[]).map(x=>`${Number(x.qty)||1}× ${escapeHtml(x.name)}${x.size?' · '+escapeHtml(x.size):''}${x.flavor?' · '+escapeHtml(x.flavor):''}`).join('<br>')||'Order details not available';}
function billDetails(a){const order=billOrder(a),payments=entries.filter(e=>e.order_id===a.order_id).sort((x,y)=>new Date(x.recorded_at)-new Date(y.recorded_at)),paid=Number(a.balance)===0;
 return `<section class="barista-order-card" style="margin:12px 0 0"><b>Order #${escapeHtml(String(order?.no||''))}</b><p>Ordered: ${escapeHtml(order?.date&&order?.time?order.date+' · '+order.time:dateTime(a.created_at))}<br>Pay Later recorded: ${escapeHtml(dateTime(a.created_at))}</p><div>${orderLines(order)}</div><p>Bill: ${money(a.total)} · Cash paid: ${money(a.cash_paid)} · GCash paid: ${money(a.gcash_paid)}<br><b>${paid?'Fully paid':'Remaining: '+money(a.balance)}</b></p><b>Payments</b>${payments.map(e=>`<div class="history-thumb-item" style="font-size:14px;margin-top:8px"><span>${escapeHtml(dateTime(e.recorded_at))} · ${e.method==='cash'?'Cash':'GCash'}</span><span>${money(e.amount)}</span></div>`).join('')||'<p>No payments yet.</p>'}${paid?`<p><b>Fully paid on:</b> ${escapeHtml(dateTime(payments.at(-1)?.recorded_at||a.created_at))}</p>`:`<button class="secondary" style="margin-top:12px" onclick="KBRDeferred.collect('${a.order_id}')">Record partial / full payment</button>`}</section>`;
}
function render(){const host=document.getElementById('baristaPayLaterView');if(!host)return;const active=accounts.filter(a=>!a.cancelled&&a.customer_name),balance=active.reduce((sum,a)=>sum+Number(a.balance),0),groups=new Map();
 for(const a of active){const key=a.customer_name.trim().replace(/\s+/g,' ').toLowerCase();if(!groups.has(key))groups.set(key,{key,name:a.customer_name.trim(),bills:[],balance:0});const group=groups.get(key);group.bills.push(a);group.balance+=Number(a.balance);}
 host.innerHTML=`<h3>Pay Later / Utang</h3><p>Total outstanding: <b>${money(balance)}</b></p><label><input id="showSettledBills" type="checkbox" ${window.kbrShowSettled?'checked':''}> Show fully paid customers</label><button class="secondary" onclick="KBRDeferred.refresh()">Refresh</button><div id="deferredBills" class="history-thumb-grid" style="align-items:start"></div>`;
 const toggle=document.getElementById('showSettledBills');toggle.onchange=()=>{window.kbrShowSettled=toggle.checked;render();};const visible=[...groups.values()].filter(g=>g.balance>0||window.kbrShowSettled);
 document.getElementById('deferredBills').innerHTML=visible.length?visible.map(g=>{const open=expandedCustomers.has(g.key),outstanding=g.bills.filter(a=>Number(a.balance)>0),preview=outstanding.length?outstanding:g.bills;
 return `<details class="history-thumb" data-customer-key="${escapeHtml(g.key)}" ${open?'open':''} style="${open?'grid-column:1 / -1;':''}"><summary style="cursor:pointer;list-style:none"><div class="history-thumb-head"><b>${escapeHtml(g.name)}</b><span class="history-thumb-total">${money(g.balance)}</span></div><div class="history-thumb-meta">Current unpaid bill · ${outstanding.length} outstanding ${outstanding.length===1?'transaction':'transactions'}</div><div class="history-thumb-items">${preview.slice(0,3).map(a=>`<div><b>Order #${escapeHtml(String(billOrder(a)?.no||''))}</b><br>${orderLines(billOrder(a))}</div>`).join('')}${preview.length>3?`<div>+ ${preview.length-3} more transactions</div>`:''}</div><div class="history-thumb-meta" style="margin-top:10px;font-weight:800">Open for full transactions and payments ▾</div></summary><div style="font-size:15px;margin-top:14px"><b>${escapeHtml(g.name)} · Current bill: ${money(g.balance)}</b><p>${g.bills.length} ${g.bills.length===1?'transaction':'transactions'} · includes fully paid bills</p>${g.bills.map(billDetails).join('')}</div></details>`;}).join(''):'<p>No outstanding Pay Later bills.</p>';
 for(const details of host.querySelectorAll?.('details[data-customer-key]')||[])details.ontoggle=()=>{if(details.isConnected===false)return;const key=details.dataset.customerKey;if(details.open)expandedCustomers.add(key);else expandedCustomers.delete(key);details.style.gridColumn=details.open?'1 / -1':'';};
}
function collect(id){const a=accounts.find(a=>a.order_id===id);if(!a)return;KBRSyncUI.screen('Record payment',a.customer_name+' · Remaining '+money(a.balance),[['Back',()=>KBRSyncUI.close()]]);const form=document.createElement('form');form.innerHTML=`<label>Amount paid<input id="deferredCollectionCash" name="amount" type="text" inputmode="decimal" pattern="[0-9]+([.][0-9]{0,2})?" max="${a.balance}" required></label>${cashPad('deferredCollectionCash',[5,10,15,20])}<label>Payment method<select name="method"><option value="cash">Cash</option><option value="gcash">GCash</option></select></label><button type="submit">Save payment received</button>`;document.querySelector('#cloudScreen .cloud-box').append(form);form.onsubmit=async e=>{e.preventDefault();if(!Number.isFinite(Number(form.elements.amount.value))||Number(form.elements.amount.value)<=0||Number(form.elements.amount.value)>Number(a.balance)){alert('Enter a positive amount up to the remaining balance.');return;}await window.savePaymentArrangement('kbr_collect_payment',{p_order:id,p_amount:Number(form.elements.amount.value),p_method:form.elements.method.value,p_operation:KBRCloud.uuid()});};}
return {panel,refresh,render,collect,cashQuick,cashKey};})();
