'use strict';
window.KBRDeferred=(()=>{
let accounts=[],entries=[],loading=false;
function money(n){return peso(Number(n)||0);}
function panel(){const order=getCurrentBaristaOrder(),total=pendingOrderTotal(order),host=document.getElementById('baristaPaymentPanel');if(!order||!host)return;
 const later=selectedBaristaPayment==='pay-later';
 host.innerHTML=`<form id="arrangementForm" class="barista-pay-panel"><b>${later?'Pay Later / Utang':'Cash + GCash split payment'}</b><p>Total: ${money(total)}</p>${later?'<label>Customer name<input name="customer" required minlength="2" maxlength="100" autocomplete="off" placeholder="Who will pay this bill?"></label>':''}<label>Cash paid now<input name="cash" type="number" min="0" max="${total}" step="0.01" value="${Math.min(Number(cashReceived)||0,total)}" required></label><label>GCash paid now<input name="gcash" type="number" min="0" max="${total}" step="0.01" value="0" required></label><p id="arrangementBalance"></p><p class="muted">${later?'Enter zero for amounts not paid. The remaining amount stays on this customer’s bill.':'Confirm the GCash transfer before saving. Cash and GCash must cover the full bill.'}</p><button type="submit" class="barista-close-pay">${later?'Confirm Pay Later':'Confirm split payment'}</button></form>`;
 const form=document.getElementById('arrangementForm'),update=()=>{const debt=Math.round((total-Number(form.elements.cash.value)-Number(form.elements.gcash.value))*100)/100;document.getElementById('arrangementBalance').textContent='Remaining: '+money(debt);};form.oninput=update;update();
 form.onsubmit=async e=>{e.preventDefault();const cash=Number(form.elements.cash.value),gcash=Number(form.elements.gcash.value);if(!later&&Math.abs(cash+gcash-total)>0.001){alert('Cash and GCash must equal the bill total. Use Pay Later for an unpaid balance.');return;}await window.savePaymentArrangement('kbr_arrange_payment',{p_order:order._cloudId,p_revision:order._cloudRevision,p_cash:cash,p_gcash:gcash,p_customer:form.elements.customer?.value||'',p_operation:KBRCloud.uuid()});};
}
async function refresh(){if(loading)return;loading=true;try{const result=await Promise.all([KBRCloud.rows('/rest/v1/kbr_payment_accounts?select=*&order=created_at.desc'),KBRCloud.rows('/rest/v1/kbr_payment_entries?select=*&order=recorded_at.asc')]);accounts=result[0];entries=result[1];render();}catch(e){const host=document.getElementById('baristaPayLaterView');if(host&&baristaView==='pay-later')host.innerHTML='<p>Could not load Pay Later bills. Check your connection and try again.</p><button onclick="KBRDeferred.refresh()">Retry</button>';}finally{loading=false;}}
function render(){const host=document.getElementById('baristaPayLaterView');if(!host)return;const active=accounts.filter(a=>!a.cancelled&&a.customer_name),balance=active.reduce((sum,a)=>sum+Number(a.balance),0);
 host.innerHTML=`<h3>Pay Later / Utang</h3><p>Total outstanding: <b>${money(balance)}</b></p><label><input id="showSettledBills" type="checkbox" onchange="KBRDeferred.render()" ${window.kbrShowSettled?'checked':''}> Show fully paid bills</label><button class="secondary" onclick="KBRDeferred.refresh()">Refresh</button><div id="deferredBills"></div>`;
 const toggle=document.getElementById('showSettledBills');toggle.onchange=()=>{window.kbrShowSettled=toggle.checked;render();};const visible=active.filter(a=>Number(a.balance)>0||window.kbrShowSettled);
 document.getElementById('deferredBills').innerHTML=visible.length?visible.map(a=>{const order=[...pendingOrders,...servedUnpaidOrders,...unservedPaidOrders].find(o=>o._cloudId===a.order_id)||history.find(r=>r._cloudId===a.order_id),payments=entries.filter(e=>e.order_id===a.order_id);
 return `<section class="barista-order-card"><h3>${escapeHtml(a.customer_name)} · Order #${escapeHtml(String(order?.no||''))}</h3><p>${new Date(a.created_at).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</p><p>${(order?.items||[]).map(x=>`${Number(x.qty)||1}× ${escapeHtml(x.name)} (${escapeHtml(x.size||'')})`).join('<br>')}</p><p>Bill: ${money(a.total)} · Cash paid: ${money(a.cash_paid)} · GCash paid: ${money(a.gcash_paid)}</p><p><b>${Number(a.balance)>0?'Remaining: '+money(a.balance):'Fully paid'}</b></p><details><summary>Payment history (${payments.length})</summary>${payments.map(e=>`<p>${new Date(e.recorded_at).toLocaleString('en-PH',{timeZone:'Asia/Manila'})} · ${e.method==='cash'?'Cash':'GCash'} · ${money(e.amount)}</p>`).join('')||'<p>No payments yet.</p>'}</details>${Number(a.balance)>0?`<button class="secondary" onclick="KBRDeferred.collect('${a.order_id}')">Record partial / full payment</button>`:''}</section>`;}).join(''):'<p>No outstanding Pay Later bills.</p>';
}
function collect(id){const a=accounts.find(a=>a.order_id===id);if(!a)return;KBRSyncUI.screen('Record payment',a.customer_name+' · Remaining '+money(a.balance),[['Back',()=>KBRSyncUI.close()]]);const form=document.createElement('form');form.innerHTML=`<label>Amount paid<input name="amount" type="number" step="0.01" min="0.01" max="${a.balance}" required></label><label>Payment method<select name="method"><option value="cash">Cash</option><option value="gcash">GCash</option></select></label><button type="submit">Save payment received</button>`;document.querySelector('#cloudScreen .cloud-box').append(form);form.onsubmit=async e=>{e.preventDefault();await window.savePaymentArrangement('kbr_collect_payment',{p_order:id,p_amount:Number(form.elements.amount.value),p_method:form.elements.method.value,p_operation:KBRCloud.uuid()});};}
return {panel,refresh,render,collect};})();
