'use strict';
window.KBRShift=(()=>{
let shifts=[],events=[],loading=false,saving=false;let countForm=null,countKind='',denomination=1,countText='';const quantities={};const denominations=[1,5,10,20,50,100,500,1000];const queue='kbr_drawer_action_v1';const nameKey='kbr_staff_display_name_'+(KBRCloud.session()?.user?.id||'staff');
const money=n=>peso(Number(n)||0),time=t=>new Date(t).toLocaleString('en-PH',{timeZone:'Asia/Manila'});
function active(){return shifts.find(s=>s.status==='open');}
function totals(s){const rows=events.filter(e=>e.shift_id===s.id);return {cash:Number(s.opening_cash)+rows.reduce((n,e)=>n+Number(e.cash),0),gcash:rows.reduce((n,e)=>n+Number(e.gcash),0),cashPayments:rows.filter(e=>e.kind==='payment').reduce((n,e)=>n+Number(e.cash),0),added:rows.filter(e=>e.kind==='cash-in').reduce((n,e)=>n+Number(e.cash),0),out:-rows.filter(e=>e.kind==='cash-out').reduce((n,e)=>n+Number(e.cash),0)};}
async function refresh(prompt=false){if(loading)return;loading=true;try{shifts=await KBRCloud.rows('/rest/v1/kbr_shifts?select=*&order=opened_at.desc&limit=20');events=shifts.length?await KBRCloud.rows('/rest/v1/kbr_shift_events?shift_id=in.('+shifts.map(s=>s.id).join(',')+')&select=*&order=recorded_at.desc'):[];render();if(prompt&&!active())action('open');}catch(e){if(baristaView==='shift')document.getElementById('baristaShiftView').innerHTML='<p>Could not load the cash drawer.</p><button onclick="KBRShift.refresh()">Retry</button>';}finally{loading=false;}}
function render(){const host=document.getElementById('baristaShiftView');if(!host)return;const s=active(),pending=KBRCloud.read(queue),t=s?totals(s):null;
 host.innerHTML=`<h3>Shift / Cash Drawer</h3>${pending?'<p>A drawer change is waiting for confirmation.</p><button onclick="KBRShift.retry()">Retry saved drawer change</button>':''}${s?`<p>Opened by ${escapeHtml(s.opened_name)} · ${time(s.opened_at)}</p><div class="history-total-strip"><div class="history-total-card"><small>Opening cash</small><b>${money(s.opening_cash)}</b></div><div class="history-total-card"><small>Cash payments received</small><b>${money(t.cashPayments)}</b></div><div class="history-total-card"><small>Cash In amount</small><b>${money(t.added)}</b></div><div class="history-total-card"><small>Cash Out amount</small><b>${money(t.out)}</b></div><div class="history-total-card"><small>Current cash · expected</small><b>${money(t.cash)}</b></div><div class="history-total-card"><small>GCash received · separate from drawer</small><b>${money(t.gcash)}</b></div></div><div class="barista-actions" style="margin:14px 0"><button onclick="KBRShift.action('cash-in')">Cash In</button><button onclick="KBRShift.action('cash-out')">Cash Out</button><button onclick="KBRShift.action('handover')">Cash Handover</button><button onclick="KBRShift.action('close')">Close Shop</button></div><p class="muted">Handover keeps the shop shift open for the next barista. Record actual refunds through Cash Out; cancelling an order alone does not remove money from the drawer.</p>${eventList(s)}`:'<p>Shop shift is closed. Count the drawer before accepting payments.</p><button onclick="KBRShift.action(\'open\')">Open Shift</button>'}<h3>Previous shifts</h3>${shifts.filter(x=>x.status==='closed').map(x=>`<details class="barista-order-card"><summary>${time(x.opened_at)} · ${escapeHtml(x.opened_name)} → ${escapeHtml(x.closed_name||'')} · Counted ${money(x.closing_count)}</summary><p>Closed: ${time(x.closed_at)}<br>Expected: ${money(x.expected_cash)} · Difference: ${money(x.variance)}</p>${eventList(x)}</details>`).join('')||'<p>No closed shifts yet.</p>'}`;
}
function eventList(s){const rows=events.filter(e=>e.shift_id===s.id);return `<details><summary>Drawer activity (${rows.length})</summary>${rows.map(e=>`<p>${time(e.recorded_at)} · ${escapeHtml(e.kind)} · ${escapeHtml(e.staff_name)}<br>${e.kind==='payment'?`Cash ${money(e.cash)} · GCash ${money(e.gcash)}`:e.kind==='handover'||e.kind==='close'?`Counted ${money(e.counted)} · Expected ${money(e.expected)} · Difference ${money(e.variance)}`:e.kind==='opening'?`Opening ${money(e.counted)}`:money(e.cash)} · ${escapeHtml(e.note||'')}${Object.keys(e.denominations||{}).length?'<br>Count: '+Object.entries(e.denominations).filter(([n,q])=>Number(q)>0).map(([n,q])=>'₱'+n+' × '+q).join(' · '):''}</p>`).join('')}</details>`;}
function countMarkup(){return `<div class="denomination-grid">${denominations.map(n=>`<button type="button" id="denom${n}" onclick="KBRShift.selectDenom(${n})">₱${n}<br><span id="denomQty${n}">0 pieces</span></button>`).join('')}</div><p id="selectedDenomination"></p><label>Number of pieces<input id="denomQuantity" type="text" inputmode="numeric" value="0" readonly></label><div class="count-keypad">${[1,2,3,4,5,6,7,8,9].map(n=>`<button type="button" onclick="KBRShift.countKey('${n}')">${n}</button>`).join('')}<button type="button" onclick="KBRShift.countKey('clear')">Clear</button><button type="button" onclick="KBRShift.countKey('0')">0</button><button type="button" onclick="KBRShift.countKey('back')" aria-label="Delete last digit">⌫</button></div>`;}
function selectDenom(n){if(!denominations.includes(n))return;denomination=n;countText='';updateCount();}
function countKey(key){if(!countForm)return;if(key==='clear')countText='0';else if(key==='back')countText=(countText||String(quantities[denomination]||0)).slice(0,-1)||'0';else if(/^\d$/.test(key))countText=(countText+key).replace(/^0+(?=\d)/,'');else return;if(countText.length>7||Number(countText)>1000000){countText=String(quantities[denomination]||0);return;}quantities[denomination]=Number(countText)||0;updateCount();}
function updateCount(){if(!countForm)return;for(const n of denominations){document.getElementById('denomQty'+n).textContent=quantities[n]+' pieces · '+money(n*quantities[n]);document.getElementById('denom'+n).classList.toggle('selected',n===denomination);}document.getElementById('selectedDenomination').textContent='Selected: ₱'+denomination+' · enter number of pieces';document.getElementById('denomQuantity').value=quantities[denomination];countForm.elements.amount.value=denominations.reduce((sum,n)=>sum+n*quantities[n],0);countForm.oninput?.();}
function action(kind){if(saving)return;if(KBRCloud.read(queue)){retry();return;}const s=active();if(kind!=='open'&&!s){refresh(true);return;}const labels={open:'Open Shop Shift','cash-in':'Cash In — add change / money','cash-out':'Cash Out — supplies / refund',handover:'Cash Handover',close:'Close Shop'},count=['open','handover','close'].includes(kind),t=s?totals(s):null;
 KBRSyncUI.screen(labels[kind],count?'Count the actual cash in the drawer.':'Record the amount and purpose.',[['Back',()=>KBRSyncUI.close()]]);
 const form=document.createElement('form');form.innerHTML=`<label>Your name<input name="staff" required minlength="2" maxlength="100" value="${escapeHtml(localStorage.getItem(nameKey)||'')}"></label><label>${count?'Total cash counted':'Amount'}<input name="amount" type="number" min="${count?0:0.01}" step="0.01" ${count?'readonly value="0"':''} required></label>${count?countMarkup():''}<label>${kind==='handover'?'Handover to / note':'Purpose / note'}<textarea name="note" maxlength="500" ${!count?'required minlength="3"':''}></textarea></label>${t&&count?`<p>Expected drawer cash: ${money(t.cash)}</p><p id="drawerVariance"></p>`:''}${kind==='close'?'<label>Manager PIN (required for a shortage or excess)<input name="pin" type="password" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" autocomplete="off"></label>':''}<button type="submit">Save ${labels[kind]}</button>`;document.querySelector('#cloudScreen .cloud-box').append(form);
 if(count){countForm=form;countKind=kind;for(const n of denominations)quantities[n]=0;denomination=1;countText='';updateCount();}
 form.oninput=()=>{const el=document.getElementById('drawerVariance');if(el)el.textContent='Difference: '+money(Number(form.elements.amount.value)-t.cash);};
 form.onsubmit=async e=>{e.preventDefault();const args={p_kind:kind,p_amount:Number(form.elements.amount.value),p_note:form.elements.note.value,p_staff:form.elements.staff.value,p_operation:KBRCloud.uuid(),p_shift:s?.id||null,p_pin:form.elements.pin?.value||'',p_denominations:count?{...quantities}:{}};localStorage.setItem(nameKey,args.p_staff);if(form.elements.pin)form.elements.pin.value='';await save(args);};
}
async function save(args){if(saving)return;saving=true;const safe={...args,p_pin:''};localStorage.setItem(queue,JSON.stringify(safe));KBRSyncUI.screen('Saving drawer change…','Please wait for confirmation.');try{const result=await KBRCloud.rpc('kbr_cash_drawer_action',args);if(result.error){localStorage.removeItem(queue);throw Object.assign(Error(result.error),{definite:true});}localStorage.removeItem(queue);await refresh();KBRSyncUI.close();if(args.p_kind==='handover')KBRSyncUI.screen('Cash handover recorded','The shop shift remains open for the next barista.',[['Sign out',()=>KBRCloud.logout()],['Continue',()=>KBRSyncUI.close()]]);}catch(e){if(e.definite||e.status===400)localStorage.removeItem(queue);KBRSyncUI.screen('Drawer change not confirmed',e.message,[['Review drawer',()=>{KBRSyncUI.close();refresh();}]]);}finally{saving=false;}}
function retry(){const args=KBRCloud.read(queue);if(!args)return;args.p_pin='';KBRSyncUI.screen('Retry saved drawer change','The same operation ID is reused. For a closing difference, enter the manager PIN again.',[['Back',()=>KBRSyncUI.close()]]);const form=document.createElement('form');form.innerHTML='<label>Manager PIN (if needed)<input name="pin" type="password" inputmode="numeric" maxlength="4" autocomplete="off"></label><button type="submit">Retry saved change</button>';document.querySelector('#cloudScreen .cloud-box').append(form);form.onsubmit=e=>{e.preventDefault();args.p_pin=form.elements.pin.value;form.elements.pin.value='';save(args);};}
return {refresh,render,action,retry,selectDenom,countKey};})();
