'use strict';
window.KBRStaffManager=(()=>{
let profiles=[],busy=false;
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
async function load(){const host=document.getElementById('staffProfiles');try{profiles=await KBRCloud.rows('/rest/v1/kbr_baristas?select=*&order=name');host.innerHTML=profiles.map(p=>`<div class="card"><b>${escape(p.name)}</b><p>${p.active?'Active':'Removed'} · ${p.duty_day===today()?'On duty today':'Off duty'}<br>Username: ${escape(p.username||'Not set')}<br>Drink passcode: ${p.has_passcode?'Set':'Not set'}</p><button onclick="KBRStaffManager.edit('${p.id}')">${p.active?'Edit / set login':'Restore'}</button>${p.active?`<button onclick="KBRStaffManager.remove('${p.id}')">Remove barista</button>`:''}</div>`).join('');}catch(e){host.textContent=e.message;}}
function edit(id){if(busy)return;const profile=profiles.find(p=>p.id===id);KBRSyncUI.screen(profile?'Edit '+profile.name:'Add barista','Login passwords and drink redemption passcodes are separate.',[['Back',()=>KBRSyncUI.close()]]);const form=document.createElement('form');form.innerHTML=`<label>Name<input name="name" minlength="2" maxlength="40" pattern="[A-Za-z][A-Za-z -]{1,39}" required ${profile?'readonly':''} value="${escape(profile?.name||'')}"></label><label>Login username<input name="username" pattern="[a-z0-9][a-z0-9._-]{2,29}" minlength="3" maxlength="30" required ${profile?.username?'readonly':''} value="${escape(profile?.username||profile?.name.toLowerCase().replace(/ /g,'.')||'')}"></label><label>${profile?.user_id?'New password (leave blank to keep)':'Login password'}<input name="password" type="password" minlength="8" autocomplete="new-password" ${profile?.user_id?'':'required'}></label><label>${profile?.has_passcode?'New drink passcode (leave blank to keep)':'Drink redemption passcode'}<input name="passcode" type="password" inputmode="numeric" pattern="[0-9]{4,6}" maxlength="6" autocomplete="new-password" ${profile?.has_passcode?'':'required'}></label><label><input name="duty" type="checkbox" ${profile?.duty_day===today()?'checked':''}> On duty today</label><button type="submit">Save barista</button>`;document.querySelector('#cloudScreen .cloud-box').append(form);
 form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const body={action:'save',id:profile?.id||null,name:form.elements.name.value.trim(),username:form.elements.username.value.trim().toLowerCase(),password:form.elements.password.value,passcode:form.elements.passcode.value,onDuty:form.elements.duty.checked};form.elements.password.value='';form.elements.passcode.value='';try{await KBRCloud.request('/functions/v1/kbr-manage-staff',{method:'POST',body:JSON.stringify(body)});KBRSyncUI.close();await load();}catch(error){KBRSyncUI.screen('Barista was not saved',error.message+' Check that the kbr-manage-staff server function is deployed.',[['Back',()=>KBRSyncUI.close()]]);}finally{busy=false;}};
}
function remove(id){if(busy)return;const profile=profiles.find(p=>p.id===id);if(!profile)return;KBRSyncUI.screen('Remove '+profile.name,'This disables their shop access and drink redemption. Existing orders and records are retained.',[['Keep barista',()=>KBRSyncUI.close()],['Remove barista',async()=>{if(busy)return;busy=true;try{await KBRCloud.request('/functions/v1/kbr-manage-staff',{method:'POST',body:JSON.stringify({action:'remove',id})});KBRSyncUI.close();await load();}catch(e){KBRSyncUI.screen('Could not remove barista',e.message,[['Back',()=>KBRSyncUI.close()]]);}finally{busy=false;}}]]);}
return {load,edit,remove};})();
