(()=>{'use strict';const host=document.getElementById('workerClockView'),drawer=document.getElementById('baristaShiftView');let workers=[],attendance=[],profile=KBRCloud.read('kbr_clock_profile_v1',null),mode='in',selected=profile?.username||'',tab='clock',busy=false,last='';const esc=escapeHtml;
const active=()=>attendance.find(a=>a.barista_id===workers.find(w=>w.username===selected)?.id&&!a.clocked_out_at);
function timer(){const a=active(),el=document.getElementById('workerElapsed');if(!a||!el)return;const seconds=Math.max(0,Math.floor((Date.now()-Date.parse(a.clocked_in_at))/1000));el.textContent=[Math.floor(seconds/3600),Math.floor(seconds/60)%60,seconds%60].map(x=>String(x).padStart(2,'0')).join(':');}
function render(){const a=active(),w=workers.find(w=>w.username===selected);if(a&&mode!=='out'){host.innerHTML=`<div class="clock-panes"><section class="barista-order-card"><h2>${esc(w.name)}</h2><p>@${esc(w.username)}</p><p>${esc(w.position||'Barista')}</p><button id="chooseWorker">Choose another worker</button></section><section class="barista-order-card"><p>Clocked in: ${esc(new Date(a.clocked_in_at).toLocaleString('en-PH',{timeZone:'Asia/Manila'}))}</p><h1 id="workerElapsed"></h1><button id="clockOut">Clock Out</button></section></div>`;document.getElementById('clockOut').onclick=()=>{mode='out';render();};document.getElementById('chooseWorker').onclick=()=>{selected='';mode='in';render();};timer();return;}
host.innerHTML=`<form id="workerClockForm" class="clock-panes"><section class="barista-order-card"><h3>${mode==='out'?'Confirm Clock Out':'Clock In'}</h3><label>Username<select name="username" required><option value="">Select active worker</option>${workers.map(w=>`<option value="${esc(w.username)}" ${selected===w.username?'selected':''}>${esc(w.username)} · ${esc(w.name)}</option>`).join('')}</select></label><label>Drink PIN<input name="pin" type="password" inputmode="numeric" pattern="[0-9]{4,6}" minlength="4" maxlength="6" autocomplete="off" required></label><p data-clock-error role="status"></p><button type="submit">${mode==='out'?'Clock Out':'Clock In'}</button></section><section class="barista-order-card"><div class="count-keypad">${['1','2','3','4','5','6','7','8','9','Clear','0','⌫'].map(n=>`<button type="button" data-clock-key="${n}">${n}</button>`).join('')}</div></section></form>`;
const form=document.getElementById('workerClockForm');form.elements.username.onchange=()=>{selected=form.elements.username.value;mode='in';render();};for(const b of form.querySelectorAll('[data-clock-key]'))b.onclick=()=>{const input=form.elements.pin,k=b.dataset.clockKey;input.value=k==='Clear'?'':k==='⌫'?input.value.slice(0,-1):input.value.length<6?input.value+k:input.value;};
form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;form.querySelector('button[type=submit]').disabled=true;try{const r=await KBRCloud.rpc('kbr_clock_worker',{p_username:form.elements.username.value,p_pin:form.elements.pin.value,p_action:mode});form.elements.pin.value='';if(r.error)throw Error(r.error);selected=r.profile.username;profile=r.profile;localStorage.setItem('kbr_clock_profile_v1',JSON.stringify(profile));mode='in';await refresh(true);render();}catch(e){form.querySelector('[data-clock-error]').textContent=e.message;form.querySelector('button[type=submit]').disabled=false;}finally{busy=false;}};
}
async function refresh(force=false){const rows=await KBRCloud.rows('/rest/v1/kbr_worker_attendance?clocked_out_at=is.null&select=*&order=clocked_in_at.desc');const signature=JSON.stringify(rows);attendance=rows;if(force||signature!==last){last=signature;if(!document.getElementById('workerClockForm')?.elements.pin.value)render();}timer();}
async function show(name){tab=name;host.hidden=name!=='clock';drawer.hidden=name==='clock';for(const b of document.querySelectorAll('[data-shift-tab]')){b.setAttribute('aria-selected',String(b.dataset.shiftTab===name));b.style.background=b.dataset.shiftTab===name?'#d9eedc':'white';}if(name!=='clock'){KBRShift.setTab(name);await KBRShift.refresh(false);}}
for(const b of document.querySelectorAll('[data-shift-tab]'))b.onclick=()=>show(b.dataset.shiftTab);
(async()=>{if(!KBRCloud.requireLogin())return;try{if(!['owner','operator'].includes(await KBRCloud.role()))throw Error('Staff login required.');workers=await KBRCloud.rpc('kbr_clock_roster',{});await refresh(true);await show('clock');if(location.search)history.replaceState(null,'','shift-records.html');setInterval(()=>{if(!document.hidden)refresh().catch(()=>{});},5000);setInterval(timer,1000);setInterval(()=>{if(!document.hidden&&tab!=='clock')KBRShift.refresh(false);},3000);}catch(e){host.textContent='Unable to load worker clock: '+e.message;}})();
})();
